---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  require_ansible_omnibus: true
  use_sudo: false

platforms:
  - name: centos-7
    driver_config:
      username: kitchen
      dockerfile: test/Dockerfile
      #image: centos/systemd
      run_command: /usr/sbin/init
verifier:
  name: serverspec

suites:
  - name: Common
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default.yml
    verifier:
      patterns:
      - roles/deploy/spec/deploy_spec.rb
